In [ ]:
# This script generates Pollen Fluxes qualibrated with 
# the number of Lycopodium spores counted in the images, and 
# the number of Lycopodium spores added in the full annual pollen trap sample

In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent.parent))
from config1 import MONITORING_DATA

In [3]:
import pandas as pd
import numpy as np

In [ ]:
p_counts = MONITORING_DATA / "Tables_PollenCounts" / "comptages_brutauto_all_pertrap.csv" # file generated using the previous script (03_table_pollen_counts_perc.ipynb)

p_lyco = MONITORING_DATA / "3.Input_Tables/lycopodium_per_trap_calibration.csv"
p_ci = MONITORING_DATA / "3.Input_Tables/perf_fracW18env_mean2se.csv"


p_save  = MONITORING_DATA / "Tables_PollenCounts"

In [ ]:
# loading number of Lycopodium spores added in each trap sample for calibration of pollen fluxes
df_ly_tablets = pd.read_csv(p_lyco)
df_ly_tablets = df_ly_tablets[df_ly_tablets["resolution"] == "ANNUEL"]
corresp_ly = {str(df_ly_tablets["site"][i])  + "_" + str(df_ly_tablets["year"][i]) : el for i, el in enumerate(df_ly_tablets["nb_ly_persample"]) }
print(corresp_ly)
df_ly_tablets

{'D1_2019': 9666, 'D2_2019': 9666, 'W1_2019': 9666, 'W2_2019': 9666, 'W4_2019': 9666, 'W3_2019': 9666, 'D1_2020': 38664, 'D2_2020': 38664, 'W1_2020': 38664, 'W2_2020': 38664, 'W4_2020': 38664, 'W3_2020': 38664, 'D1_2021': 73628, 'D2_2021': 73628, 'W1_2021': 73628, 'W2_2021': 73628, 'W4_2021': 73628, 'W3_2021': 73628, 'D3_2022': 55044, 'D2_2022': 55044, 'W1_2022': 55044, 'W2_2022': 55044, 'W4_2022': 55044, 'W3_2022': 55044, 'D3_2023': 55044, 'D2_2023': 55044, 'W1_2023': 55044, 'W2_2023': 55044, 'W4_2023': 55044, 'W3_2023': 55044}

,year,site,month,resolution,nb_tablette,nb_ly_pertablette,nb_ly_persample
0,2019,D1,na,ANNUEL,1,9666,9666
1,2019,D2,na,ANNUEL,1,9666,9666
2,2019,W1,na,ANNUEL,1,9666,9666
3,2019,W2,na,ANNUEL,1,9666,9666
4,2019,W4,na,ANNUEL,1,9666,9666
5,2019,W3,na,ANNUEL,1,9666,9666
6,2020,D1,na,ANNUEL,4,9666,38664
7,2020,D2,na,ANNUEL,4,9666,38664
8,2020,W1,na,ANNUEL,4,9666,38664
9,2020,W2,na,ANNUEL,4,9666,38664
10,2020,W4,na,ANNUEL,4,9666,38664
11,2020,W3,na,ANNUEL,4,9666,38664
12,2021,D1,na,ANNUEL,4,18407,73628
13,2021,D2,na,ANNUEL,4,18407,73628
14,2021,W1,na,ANNUEL,4,18407,73628
15,2021,W2,na,ANNUEL,4,18407,73628
16,2021,W4,na,ANNUEL,4,18407,73628
17,2021,W3,na,ANNUEL,4,18407,73628
18,2022,D3,na,ANNUEL,4,13761,55044
19,2022,D2,na,ANNUEL,4,13761,55044
20,2022,W1,na,ANNUEL,4,13761,55044
21,2022,W2,na,ANNUEL,4,13761,55044
22,2022,W4,na,ANNUEL,4,13761,55044
23,2022,W3,na,ANNUEL,4,13761,55044
24,2023,D3,na,ANNUEL,4,13761,55044
25,2023,D2,na,ANNUEL,4,13761,55044
26,2023,W1,na,ANNUEL,4,13761,55044
27,2023,W2,na,ANNUEL,4,13761,55044
28,2023,W4,na,ANNUEL,4,13761,55044
29,2023,W3,na,ANNUEL,4,13761,55044

In [8]:

df_counts = pd.read_csv(p_counts)
df_counts.head()

   class site  year site_year  class_num      count
0  Buxus   D1  2019   D1_2019          2  53.806745
1  Buxus   D1  2020   D1_2020          2  41.644678
2  Buxus   D1  2021   D1_2021          2  24.990120
3  Buxus   D2  2020   D2_2020          2  27.706941
4  Buxus   D2  2021   D2_2021          2  30.323475

In [9]:
# Pollen fluxes per traps (without confidence interval)

df_counts["nb_ly_persample"] = [corresp_ly[k] for k in df_counts["site_year"]]

count_ly = {str(df_counts["site"][i])  + "_" + str(df_counts["year"][i]) : float(df_counts["count"][i]) for i, el in enumerate(df_counts["class"]) if el == "Lycopodium"}
print(count_ly)

df_counts["count_ly"] = [count_ly[k] for k in df_counts["site_year"]]

df_counts["count_tot_trap"] = [float(el)*float(df_counts["nb_ly_persample"][e])/float(df_counts["count_ly"][e]) for e, el in enumerate(df_counts["count"])]
df_counts["flux_cm2_an"] = [el / (2.5*2.5*np.pi) for el in df_counts["count_tot_trap"]]

df_counts.head()

{'D1_2019': 38.870025486014704, 'D1_2020': 1009.650010381336, 'D1_2021': 504.1006345044587, 'D2_2020': 956.3243105153288, 'D2_2021': 727.3064763055252, 'D2_2022': 831.4390832276634, 'D2_2023': 1304.5871653311592, 'D3_2022': 874.5345234865962, 'D3_2023': 2035.0553950336173, 'W1_2019': 17.819520385989996, 'W1_2020': 278.8249843679952, 'W1_2021': 246.37603967254063, 'W1_2022': 604.5885900705974, 'W1_2023': 1160.906006489805, 'W2_2019': 24.07139749946233, 'W2_2020': 205.41318385860987, 'W2_2021': 429.3233369078878, 'W2_2022': 673.5235960969924, 'W2_2023': 840.1867793672078, 'W3_2019': 55.91931581642962, 'W3_2020': 366.1841957411581, 'W3_2021': 292.13719623729264, 'W3_2023': 452.01869146210936, 'W4_2019': 36.71012673919627, 'W4_2020': 770.6126145975654, 'W4_2021': 1067.9156832536553, 'W4_2022': 1548.6636273913305, 'W4_2023': 2274.153763257839}

,class,site,year,site_year,class_num,count,nb_ly_persample,count_ly,count_tot_trap,flux_cm2_an
0,Buxus,D1,2019,D1_2019,2,53.806745,9666,38.870025,13380.387225,681.457526
1,Buxus,D1,2020,D1_2020,2,41.644678,38664,1009.650010,1594.760392,81.220480
2,Buxus,D1,2021,D1_2021,2,24.990120,73628,504.100635,3650.010439,185.893505
3,Buxus,D2,2020,D2_2020,2,27.706941,38664,956.324311,1120.186082,57.050609
4,Buxus,D2,2021,D2_2021,2,30.323475,73628,727.306476,3069.760699,156.341629

In [ ]:
# saving the table
# df_counts.to_csv(p_save / "qualibratedfluxes_all.csv" , index=False)

# with Confidence intervals

In [20]:

df_counts = pd.read_csv(p_counts)
df_counts.head()

   class site  year site_year  class_num      count
0  Buxus   D1  2019   D1_2019          2  53.806745
1  Buxus   D1  2020   D1_2020          2  41.644678
2  Buxus   D1  2021   D1_2021          2  24.990120
3  Buxus   D2  2020   D2_2020          2  27.706941
4  Buxus   D2  2021   D2_2021          2  30.323475

In [21]:
df_ci = pd.read_csv(p_ci)
df_ci.head()

,class,precision-mean,recall-mean,f1score-mean,nb_groundtruth-mean,precision-twose_standerr,recall-twose_standerr,f1score-twose_standerr,nb_groundtruth-twose_standerr,deviation
0,Buxus,98.311908,99.393425,98.846718,83.7,0.535767,0.476363,0.356316,0.305505,0.011092
1,Cupressaceae,94.801831,96.665584,95.703887,91.4,1.232880,1.101915,0.710316,0.326599,0.020090
2,Fraxinus,82.021163,80.992558,81.411749,27.9,2.808299,2.408340,1.885975,0.466667,-0.009978
3,IndetBlurry,97.967201,96.926702,97.436391,44.0,1.079744,0.960905,0.842009,0.000000,-0.010435
4,IndetCovered,89.464785,82.248615,85.645636,48.7,1.215468,2.616287,1.496897,0.305505,-0.080296

In [22]:
df_merge = pd.merge(df_ci[["class", "deviation"]], df_counts, on=["class"], how="left")
df_merge["count_dev"] = df_merge["count"] * (1 - df_merge["deviation"])
df_merge

      class  deviation site  year site_year  class_num       count   count_dev
0     Buxus   0.011092   D1  2019   D1_2019          2   53.806745   53.209911
1     Buxus   0.011092   D1  2020   D1_2020          2   41.644678   41.182748
2     Buxus   0.011092   D1  2021   D1_2021          2   24.990120   24.712926
3     Buxus   0.011092   D2  2020   D2_2020          2   27.706941   27.399611
4     Buxus   0.011092   D2  2021   D2_2021          2   30.323475   29.987122
..      ...        ...  ...   ...       ...        ...         ...         ...
499  VitisS   0.006422   W4  2019   W4_2019         11   82.988265   82.455311
500  VitisS   0.006422   W4  2020   W4_2020         11  160.987076  159.953211
501  VitisS   0.006422   W4  2021   W4_2021         11  166.132552  165.065643
502  VitisS   0.006422   W4  2022   W4_2022         11  363.848496  361.511849
503  VitisS   0.006422   W4  2023   W4_2023         11  803.968813  798.805697

[504 rows x 8 columns]

In [23]:
count_ly = df_merge[df_merge["class"] == "Lycopodium"]
count_ly = count_ly.rename(columns={"count": "count_ly", "deviation" : "deviation_ly", "count_dev": "count_ly_dev"})
count_ly.drop(columns=["class"], inplace=True)
count_ly.head()

     deviation_ly site  year site_year  class_num     count_ly  count_ly_dev
140     -0.001117   D1  2019   D1_2019         17    38.870025     38.913452
141     -0.001117   D1  2020   D1_2020         17  1009.650010   1010.778006
142     -0.001117   D1  2021   D1_2021         17   504.100635    504.663823
143     -0.001117   D2  2020   D2_2020         17   956.324311    957.392729
144     -0.001117   D2  2021   D2_2021         17   727.306476    728.119033

In [24]:
df_merge2 = pd.merge(df_merge, count_ly, on=["site_year", "site", "year"])
df_merge3 = pd.merge(df_merge2, df_ly_tablets[["site", "year", "nb_ly_persample"]], on=["site", "year"], how="left")
df_merge3

,class,deviation,site,year,site_year,class_num_x,count,count_dev,deviation_ly,class_num_y,count_ly,count_ly_dev,nb_ly_persample
0,Buxus,0.011092,D1,2019,D1_2019,2,53.806745,53.209911,-0.001117,17,38.870025,38.913452,9666
1,Buxus,0.011092,D1,2020,D1_2020,2,41.644678,41.182748,-0.001117,17,1009.650010,1010.778006,38664
2,Buxus,0.011092,D1,2021,D1_2021,2,24.990120,24.712926,-0.001117,17,504.100635,504.663823,73628
3,Buxus,0.011092,D2,2020,D2_2020,2,27.706941,27.399611,-0.001117,17,956.324311,957.392729,38664
4,Buxus,0.011092,D2,2021,D2_2021,2,30.323475,29.987122,-0.001117,17,727.306476,728.119033,73628
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,VitisS,0.006422,W4,2019,W4_2019,11,82.988265,82.455311,-0.001117,17,36.710127,36.751140,9666
500,VitisS,0.006422,W4,2020,W4_2020,11,160.987076,159.953211,-0.001117,17,770.612615,771.473554,38664
501,VitisS,0.006422,W4,2021,W4_2021,11,166.132552,165.065643,-0.001117,17,1067.915683,1069.108774,73628
502,VitisS,0.006422,W4,2022,W4_2022,11,363.848496,361.511849,-0.001117,17,1548.663627,1550.393816,55044
503,VitisS,0.006422,W4,2023,W4_2023,11,803.968813,798.805697,-0.001117,17,2274.153763,2276.694480,55044

In [25]:
#  PAR min (utilise min count vitis and min count ly) et max (qui utilise max count vitis et lyco)


def compute_par_ci(count_taxon, count_dev_taxon, count_lyco, count_dev_lyco, tot_ly_sample):
    area = np.pi * 2.5*2.5
    proportion_scanned_min = float(tot_ly_sample) / max(count_lyco, count_dev_lyco)
    proportion_scanned_max = float(tot_ly_sample) / min(count_lyco, count_dev_lyco)

    par_taxon_min = min(count_taxon, count_dev_taxon) * proportion_scanned_min / area
    par_taxon_max= max(count_taxon, count_dev_taxon) * proportion_scanned_max / area
    par_taxon_mean = count_taxon * (float(tot_ly_sample) / count_lyco) / area 

    return par_taxon_mean, par_taxon_min, par_taxon_max


df_merge3[["par_mean", "par_min", "par_max"]] = df_merge3.apply(
    lambda r: compute_par_ci(r["count"],r["count_dev"],r["count_ly"],r["count_ly_dev"],r["nb_ly_persample"]),axis=1,result_type="expand")

df_merge3

,class,deviation,site,year,site_year,class_num_x,count,count_dev,deviation_ly,class_num_y,count_ly,count_ly_dev,nb_ly_persample,par_mean,par_min,par_max
0,Buxus,0.011092,D1,2019,D1_2019,2,53.806745,53.209911,-0.001117,17,38.870025,38.913452,9666,681.457526,673.146631,681.457526
1,Buxus,0.011092,D1,2020,D1_2020,2,41.644678,41.182748,-0.001117,17,1009.650010,1010.778006,38664,81.220480,80.229934,81.220480
2,Buxus,0.011092,D1,2021,D1_2021,2,24.990120,24.712926,-0.001117,17,504.100635,504.663823,73628,185.893505,183.626392,185.893505
3,Buxus,0.011092,D2,2020,D2_2020,2,27.706941,27.399611,-0.001117,17,956.324311,957.392729,38664,57.050609,56.354833,57.050609
4,Buxus,0.011092,D2,2021,D2_2021,2,30.323475,29.987122,-0.001117,17,727.306476,728.119033,73628,156.341629,154.434923,156.341629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,VitisS,0.006422,W4,2019,W4_2019,11,82.988265,82.455311,-0.001117,17,36.710127,36.751140,9666,1112.878365,1104.497461,1112.878365
500,VitisS,0.006422,W4,2020,W4_2020,11,160.987076,159.953211,-0.001117,17,770.612615,771.473554,38664,411.369217,408.271263,411.369217
501,VitisS,0.006422,W4,2021,W4_2021,11,166.132552,165.065643,-0.001117,17,1067.915683,1069.108774,73628,583.352260,578.959131,583.352260
502,VitisS,0.006422,W4,2022,W4_2022,11,363.848496,361.511849,-0.001117,17,1548.663627,1550.393816,55044,658.633145,653.673087,658.633145
503,VitisS,0.006422,W4,2023,W4_2023,11,803.968813,798.805697,-0.001117,17,2274.153763,2276.694480,55044,991.058915,983.595414,991.058915

In [ ]:

# saving file
#df_merge3.to_csv(p_save /  "qualibratedfluxes_withCI_all.csv", index=False)

In [ ]:
# end