In [ ]:
# This sciprt generate the tables of percentages used to do the correspondance analysis in R:
# - per site and per year
# - per site over years

In [2]:
import pandas as pd
import os
import pickle
import numpy as np

In [3]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent.parent))
from config1 import MONITORING_DATA, classes18, fig_class_order

In [6]:
mp_pred_combined = MONITORING_DATA / "PREDICTIONS_51slides_combined/"
p_csv  = MONITORING_DATA / "Tables_for_figures" 

p_save_table = MONITORING_DATA / "Tables_PollenCounts/"

In [7]:
df_long = pd.read_csv(p_csv/ "comptages_brutauto_all_perslide.csv")

df_long.head()

  site  year      slide             class      count  class_num site_year
0   D1  2019  D1_2019_A  QuercusDeciduous  29.147301          0   D1_2019
1   D1  2020  D1_2020_A  QuercusDeciduous  25.037277          0   D1_2020
2   D1  2020  D1_2020_B  QuercusDeciduous  88.580480          0   D1_2020
3   D1  2021  D1_2021_A  QuercusDeciduous  78.337110          0   D1_2021
4   D2  2020  D2_2020_B  QuercusDeciduous  49.359799          0   D2_2020

In [5]:
df_long_2 = df_long.drop(columns="slide")
df_all = df_long_2.groupby(["class", "site", "year", "site_year", 'class_num']).mean().reset_index() 
df_all.head()

   class site  year site_year  class_num      count
0  Buxus   D1  2019   D1_2019          2  53.806745
1  Buxus   D1  2020   D1_2020          2  20.822339
2  Buxus   D1  2021   D1_2021          2  24.990120
3  Buxus   D2  2020   D2_2020          2  13.853471
4  Buxus   D2  2021   D2_2021          2  30.323475

In [6]:

df_siteyear_perc = df_all[df_all["class"].isin(fig_class_order)]

df_siteyear_perc.loc[:, "proportion"] = df_siteyear_perc["count"] * 100 / df_siteyear_perc.groupby(["site", "year"])["count"].transform("sum")

df_siteyear_perc

      class site  year site_year  class_num       count  proportion
0     Buxus   D1  2019   D1_2019          2   53.806745    6.734485
1     Buxus   D1  2020   D1_2020          2   20.822339    1.226623
2     Buxus   D1  2021   D1_2021          2   24.990120    1.016147
3     Buxus   D2  2020   D2_2020          2   13.853471    0.795045
4     Buxus   D2  2021   D2_2021          2   30.323475    0.712326
..      ...  ...   ...       ...        ...         ...         ...
499  VitisS   W4  2019   W4_2019         11   82.988265    3.651658
500  VitisS   W4  2020   W4_2020         11   80.493538    3.775502
501  VitisS   W4  2021   W4_2021         11   83.066276    2.248256
502  VitisS   W4  2022   W4_2022         11  121.282832    2.812331
503  VitisS   W4  2023   W4_2023         11  267.989604    2.621540

[392 rows x 7 columns]

In [7]:

df_siteyear_perc = df_siteyear_perc.pivot(index="site_year", columns="class", values="proportion").reset_index()
df_siteyear_perc.columns.name = None
df_siteyear_perc.set_index('site_year', inplace=True)

df_siteyear_perc = df_siteyear_perc[fig_class_order]
df_siteyear_perc.reset_index()

df_siteyear_perc.to_csv(p_save_table / "percentages_persiteperyear_forAC_withOther.csv")

df_siteyear_perc

,QuercusDeciduous,QuercusIlex,Buxus,Phillyrea,Fraxinus,Olea,Cupressaceae,Pistacia,Poaceae,Plantago,VitisF,VitisS,Pinaceae,Other
site_year,,,,,,,,,,,,,,
D1_2019,3.648094,9.803933,6.734485,0.714618,0.982000,1.217762,12.221043,13.452162,3.736070,1.032800,3.044098,1.998502,8.565359,32.849074
D1_2020,3.346554,7.682511,1.226623,1.365324,2.067332,1.657528,12.321349,21.556190,6.342098,1.415773,1.621260,0.533793,7.274859,31.588805
D1_2021,3.185339,18.102384,1.016147,1.908326,1.325394,3.228025,25.185508,2.869013,6.714866,1.750739,0.814738,0.920917,13.254804,19.723800
D2_2020,1.914914,7.049384,0.795045,0.658233,1.789808,1.364800,11.365855,6.810309,21.223123,3.646133,1.217432,0.573340,10.806948,30.784678
D2_2021,2.260425,13.249129,0.712326,1.547870,1.379503,2.623595,14.582412,0.846074,29.131131,8.070595,0.890232,1.801655,5.772387,17.132665
D2_2022,2.838809,6.103901,0.678142,0.598402,1.106758,0.684252,10.453746,5.653759,19.951194,2.648666,2.171963,0.569689,18.821008,27.719710
D2_2023,1.601990,4.165016,0.405681,0.591231,0.783224,1.001421,6.598727,5.360586,21.966411,12.493033,1.000155,0.666650,10.306196,33.059679
D3_2022,4.741863,8.928896,0.520304,0.616935,0.618178,3.061851,6.424071,8.501051,4.060081,1.010903,9.719073,0.851398,10.785336,40.160061
D3_2023,2.347500,6.260507,0.752095,0.551558,0.721296,1.909146,13.589774,3.875740,5.141512,2.429789,16.821278,2.187251,7.730482,35.682074
W1_2019,3.968408,9.564971,2.663934,49.812599,11.503126,2.143613,4.786058,0.577656,1.063114,0.262510,2.072823,0.418206,4.739300,6.423683
W1_2020,1.918462,6.869217,1.560263,22.746226,12.588895,3.728195,4.634403,1.712422,1.859161,0.566426,9.262026,0.440297,6.458367,25.655639
W1_2021,2.370605,9.155399,1.806440,16.630269,6.923977,3.049260,5.539096,0.943729,1.881638,0.483075,5.323205,0.697908,21.455948,23.739448
W1_2022,3.408672,5.880723,2.606912,15.891838,17.384106,10.928486,2.863671,1.705105,1.171274,0.895939,10.700231,0.385775,6.396918,19.780349
W1_2023,2.978683,6.723368,0.704946,2.059975,2.778585,5.032909,3.985501,4.220397,3.010080,1.058879,26.366266,0.578988,8.755431,31.745994
W2_2019,4.557574,55.675779,1.212266,0.882610,0.463165,0.882513,15.604262,0.831637,0.763830,0.512284,2.893530,1.713388,5.273163,8.734000
W2_2020,3.430282,65.994012,0.264056,0.507460,0.422819,0.798593,5.047243,0.731879,1.287822,0.321536,5.097533,0.580907,5.584695,9.931165
W2_2021,6.505064,48.184134,0.390247,0.830737,0.482195,1.076699,5.760531,1.697271,1.256383,0.961219,2.251745,0.855997,5.694404,24.053374
W2_2022,7.076812,28.098515,0.538606,0.360263,0.459953,0.829779,7.547629,4.182251,7.472601,1.749166,5.448977,1.208271,11.722013,23.305164
W2_2023,4.606551,24.282425,0.365711,0.265758,0.224725,0.891887,5.289386,3.854070,1.637028,1.280637,5.753214,0.774870,7.592725,43.181015
W3_2019,3.706710,12.966129,59.024295,3.748767,2.732707,0.415919,5.038456,0.681808,0.626294,0.203292,0.605676,0.657778,3.000688,6.591481
W3_2020,1.137605,5.100310,21.841988,19.869734,19.389578,2.408220,2.082089,2.071470,1.297189,0.355960,0.722048,0.223499,3.824490,19.675819
W3_2021,3.305865,22.686701,11.453967,10.087470,6.635057,2.510219,6.635950,0.736313,3.052270,0.549273,0.629288,0.301460,7.434637,23.981530
W3_2023,2.222897,7.473269,1.611466,6.865845,8.337679,9.607338,2.232556,1.630186,3.207533,1.508738,4.144786,0.914104,14.262356,35.981248
W4_2019,7.210277,14.893076,2.856064,7.262266,38.714522,2.128209,8.153784,0.332701,1.869144,0.336921,0.788787,3.651658,4.129134,7.673457
W4_2020,2.253126,8.268362,1.962248,8.295172,18.463496,1.473246,12.720076,4.483560,5.362800,0.825814,0.796920,3.775502,7.295565,24.024114
W4_2021,3.899954,11.999015,1.542304,4.876110,12.960437,3.760834,14.128804,2.507397,5.246979,1.081162,1.835539,2.248256,12.659171,21.254038
W4_2022,3.396571,7.719488,2.577328,6.845070,17.171568,3.286459,9.171810,4.036540,3.212245,1.027185,2.248580,2.812331,7.291010,29.203816
W4_2023,1.313279,4.160377,2.352106,10.812279,22.714997,4.031535,6.081137,4.568603,3.829677,1.230787,1.670159,2.621540,4.100778,30.512745

### per site (over years)

In [9]:
df_site_perc = df_all[df_all["class"].isin(fig_class_order)]
df_site_perc

      class site  year site_year  class_num       count
0     Buxus   D1  2019   D1_2019          2   53.806745
1     Buxus   D1  2020   D1_2020          2   20.822339
2     Buxus   D1  2021   D1_2021          2   24.990120
3     Buxus   D2  2020   D2_2020          2   13.853471
4     Buxus   D2  2021   D2_2021          2   30.323475
..      ...  ...   ...       ...        ...         ...
499  VitisS   W4  2019   W4_2019         11   82.988265
500  VitisS   W4  2020   W4_2020         11   80.493538
501  VitisS   W4  2021   W4_2021         11   83.066276
502  VitisS   W4  2022   W4_2022         11  121.282832
503  VitisS   W4  2023   W4_2023         11  267.989604

[392 rows x 6 columns]

In [10]:

df_site_perc= df_site_perc[["class", "site", "count"]].groupby(["class", "site"]).mean().reset_index()
df_site_perc.loc[:, "proportion"] = df_site_perc["count"] * 100 / df_site_perc.groupby(["site"])["count"].transform("sum")

df_site_perc

     class site       count  proportion
0    Buxus   D1   33.206401    2.010150
1    Buxus   D2   19.023096    0.599816
2    Buxus   D3   33.128295    0.672984
3    Buxus   W1   54.320978    2.024713
4    Buxus   W2   10.695511    0.504405
..     ...  ...         ...         ...
93  VitisS   D3   85.225976    1.731322
94  VitisS   W1   12.088776    0.450587
95  VitisS   W2   21.080125    0.994147
96  VitisS   W3   12.973350    0.517567
97  VitisS   W4  127.164103    2.809083

[98 rows x 4 columns]

In [11]:

df_site_perc = df_site_perc.pivot(index="site", columns="class", values="proportion").reset_index()
df_site_perc.columns.name = None
df_site_perc.set_index('site', inplace=True)

df_site_perc = df_site_perc[fig_class_order]
df_site_perc.reset_index()


df_site_perc

,QuercusDeciduous,QuercusIlex,Buxus,Phillyrea,Fraxinus,Olea,Cupressaceae,Pistacia,Poaceae,Plantago,VitisF,VitisS,Pinaceae,Other
site,,,,,,,,,,,,,,
D1,3.315166,13.195350,2.010150,1.529880,1.524171,2.365982,18.688970,10.976219,6.106940,1.520256,1.450416,0.962042,10.450439,25.904019
D2,2.037302,7.878176,0.599816,0.922443,1.166405,1.551729,10.466741,4.085424,23.989304,8.429744,1.155487,1.021266,10.033465,26.662700
D3,3.164701,7.171234,0.672984,0.573871,0.686101,2.302566,11.144105,5.454368,4.772417,1.945520,14.397280,1.731322,8.773110,37.210420
W1,3.174173,6.813410,2.024713,18.385130,12.296037,7.208284,3.690802,2.102663,1.684608,0.790910,12.746686,0.450587,7.148097,21.483900
W2,5.456543,41.706703,0.504405,0.520821,0.409102,0.889269,7.247409,2.579450,3.106562,1.080910,4.533795,0.994147,7.782291,23.188593
W3,2.685859,11.773600,30.038987,9.816750,8.907311,2.938533,4.068302,1.228093,1.716589,0.535995,1.252857,0.517567,6.016410,18.503146
W4,2.813056,7.582582,2.276709,8.493894,21.272516,3.413313,8.817093,3.697454,3.890950,1.039677,1.636614,2.809083,6.409400,25.847660

In [12]:
# saving
df_site_perc.to_csv(p_save_table / "percentages_persite_forAC_withOther.csv")

In [ ]:
# end